# Generated by Django 3.1.4 on 2021-12-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_productcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategorie',
        ),
    ]
