# Generated by Django 3.1.4 on 2021-12-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211219_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategorie',
            new_name='ProductCategories',
        ),
    ]
